/*
 * font.h - The console face (kernel/core/font8x8.c, generated by
 * tools/mkfont.py from the glyph art in that script).
 *
 * A glyph is 8 rows of 8 pixels with the leftmost pixel in bit 7; the
 * drawn part is 5 wide and 7 tall, so the spare column and row are the
 * spacing between cells. The table covers 0x20..0x7e and ends with a box
 * for every byte the console cannot draw.
 */

#ifndef KERNEL_FONT_H
#define KERNEL_FONT_H

#include <stdint.h>

#define FONT_WIDTH  8u
#define FONT_HEIGHT 8u
#define FONT_FIRST  0x20u
#define FONT_LAST   0x7eu
#define FONT_GLYPHS (FONT_LAST - FONT_FIRST + 2u)   /* + the replacement box */
#define FONT_BOX    (FONT_GLYPHS - 1u)

extern const uint8_t font8x8[FONT_GLYPHS][FONT_HEIGHT];

/* The glyph index for a byte: its own, or the box. */
static inline unsigned font_index(unsigned char c)
{
    return (c >= FONT_FIRST && c <= FONT_LAST) ? (unsigned)(c - FONT_FIRST) : FONT_BOX;
}

#endif /* KERNEL_FONT_H */
