#ifndef _ERRNO_H
#define _ERRNO_H
#include <uapi/cosmo/syscall.h>
extern int errno;
#define EPERM COSMO_EPERM
#define ENOENT COSMO_ENOENT
#define ESRCH COSMO_ESRCH
#define EINTR COSMO_EINTR
#define EIO COSMO_EIO
#define E2BIG COSMO_E2BIG
#define ENOEXEC COSMO_ENOEXEC
#define EBADF COSMO_EBADF
#define ECHILD COSMO_ECHILD
#define EAGAIN COSMO_EAGAIN
#define ENOMEM COSMO_ENOMEM
#define EACCES COSMO_EACCES
#define EFAULT COSMO_EFAULT
#define EBUSY COSMO_EBUSY
#define EEXIST COSMO_EEXIST
#define EXDEV COSMO_EXDEV
#define ENODEV COSMO_ENODEV
#define ENOTDIR COSMO_ENOTDIR
#define EISDIR COSMO_EISDIR
#define EINVAL COSMO_EINVAL
#define EMFILE COSMO_EMFILE
#define ENOTTY COSMO_ENOTTY
#define EFBIG COSMO_EFBIG
#define ENOSPC COSMO_ENOSPC
#define ESPIPE COSMO_ESPIPE
#define EROFS COSMO_EROFS
#define EPIPE COSMO_EPIPE
#define ERANGE COSMO_ERANGE
#define ENAMETOOLONG COSMO_ENAMETOOLONG
#define ENOSYS COSMO_ENOSYS
#define ENOTEMPTY COSMO_ENOTEMPTY
#define EMSGSIZE COSMO_EMSGSIZE
#define EOPNOTSUPP COSMO_EOPNOTSUPP
#define EAFNOSUPPORT COSMO_EAFNOSUPPORT
#define EADDRINUSE COSMO_EADDRINUSE
#define EADDRNOTAVAIL COSMO_EADDRNOTAVAIL
#define ECONNRESET COSMO_ECONNRESET
#define EISCONN COSMO_EISCONN
#define ENOTCONN COSMO_ENOTCONN
#define ETIMEDOUT COSMO_ETIMEDOUT
#define ECONNREFUSED COSMO_ECONNREFUSED
#define EHOSTUNREACH COSMO_EHOSTUNREACH
#endif
