#!/usr/bin/env python3
"""gen-keyring.py OUTPUT.c KEY.pub [KEY.pub ...]

Generate kernel/security's built-in trusted key table from public key
files (32-byte Ed25519 keys as hex). The key id is the first 8 bytes of
SHA-512 over the raw public key, the same derivation modsign.py and
keyring_key_id() use. Output is deterministic for reproducible builds.
"""

import hashlib
import os
import sys


def main(argv):
    if len(argv) < 3:
        sys.stderr.write(__doc__)
        return 2
    out = argv[1]
    keys = []
    for path in argv[2:]:
        with open(path) as f:
            pub = bytes.fromhex(f.read().strip())
        if len(pub) != 32:
            raise SystemExit(f"gen-keyring: {path} is not a 32-byte key")
        name = os.path.basename(path)
        if name.endswith(".pub"):
            name = name[:-4]
        keys.append((name, pub, hashlib.sha512(pub).digest()[:8]))

    def carray(b):
        return ", ".join("0x%02x" % x for x in b)

    lines = [
        "/* Generated by scripts/gen-keyring.py from the .pub files in tools/keys. Do not edit. */",
        "",
        "#include <kernel/keyring.h>",
        "",
        "const struct trusted_key keyring_builtin[] = {",
    ]
    for name, pub, kid in keys:
        lines.append("    {")
        lines.append(f"        .id = {{ {carray(kid)} }},")
        lines.append(f"        .pub = {{ {carray(pub)} }},")
        lines.append(f'        .name = "{name}",')
        lines.append("    },")
    lines.append("};")
    lines.append("")
    lines.append(f"const unsigned keyring_builtin_count = {len(keys)}u;")
    lines.append("")
    text = "\n".join(lines)
    os.makedirs(os.path.dirname(os.path.abspath(out)), exist_ok=True)
    tmp = out + ".tmp"
    with open(tmp, "w") as f:
        f.write(text)
    os.replace(tmp, out)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
